version: "3.9"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      DB_USER: admin
      DB_HOST: ${DB_HOST}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: 3306
      DB_NAME: my-sql-container
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
